spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: root
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
  application:
    name: bank-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: sdavidalex2@gmail.com
    password: cavg gpsk yomr cqzz
    protocol: smtp
    auth: true
    starttls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: sdavidalex2@gmail.com
#    password: cavg gpsk yomr cqzz
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

server:
  port: 8081

