spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sdavidalex2@gmail.com
    password: cavg gpsk yomr cqzz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true