spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: root
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    open-in-view: false
  application:
    name: bank-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
server:
  port: 8081

