spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample_db
    username: postgres
    password: root
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
  application:
    name: student-service

server:
  port: 8082