services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=test-server'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  java-app:
    image: bank-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

version: '3.8'

